# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Use this aggregated ClusterRole when you need to read "Sources".
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cloud-run-events-source-observer
  labels:
    events.cloud.google.com/release: devel
aggregationRule:
  clusterRoleSelectors:
    - matchLabels:
        duck.knative.dev/source: "true"
rules: [] # Rules are automatically filled in by the controller manager.

---
# The role is needed for the aggregated role cloud-run-events-source-observer in knative-gcp to provide readonly access to "Sources".
# The role is needed for the aggregated role source-observer in knative-eventing to provide readonly access to "Sources".
# See https://github.com/knative/eventing/blob/master/config/200-source-observer-clusterrole.yaml.
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: knative-gcp-sources-observer
  labels:
    events.cloud.google.com/release: devel
    duck.knative.dev/source: "true"
# Do not use this role directly. These rules will be added to the "cloud-run-events-source-observer" in knative-gcp and "source-observer" role in knative-eventing.
rules:
  - apiGroups:
      - "events.cloud.google.com"
    resources:
      - "cloudstoragesources"
      - "cloudpubsubsources"
      - "cloudauditlogssources"
      - "cloudschedulersources"
      - "cloudbuildsources"
    verbs:
      - get
      - list
      - watch
